- name: Extract Java .zip file
      ansible.windows.win_unzip:
        src: "C:\\temp\\jdk-22_windows-x64_bin.zip"
        dest: "C:\\Program Files\\Java"
        creates: "C:\\Program Files\\Java\\jdk-version"  # Adjust to the actual extracted directory

    - name: Set JAVA_HOME environment variable
      ansible.windows.win_environment:
        state: present
        name: JAVA_HOME
        value: "C:\\Program Files\\Java\\jdk-version"
        level: machine

    - name: Add Java to system PATH
      ansible.windows.win_environment:
        state: present
        name: Path
        value: "C:\\Program Files\\Java\\jdk-version\\bin"
        level: machine
        modify: prepend

    - name: Reboot the Windows VM if required
      ansible.windows.win_reboot:
        reboot_timeout: 120

    - name: Verify Java installation
      ansible.windows.win_command:
        cmd: "java -version"
      register: java_version_output

    - name: Display Java version
      ansible.builtin.debug:
        msg: "{{ java_version_output.stdout }}"
