apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 128Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 60s}
      - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sample-app
spec:
  hosts:
  - "sample-app.local"
  gateways:
  - sample-app-gateway
  http:
  - route:
    - destination:
        host: sample-app.wordpressns.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: sample-app.wordpressns.svc.cluster.local
        subset: canary
      weight: 0
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: sample-app
spec:
  host: sample-app.wordpressns.svc.cluster.local
  subsets:
  - name: stable
    labels:
      app: sample-app
  - name: canary
    labels:
      app: sample-app
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sample-app-gateway
spec:
  selector:
    istio: ingressgateway  # Use Istio's wordpressns ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "sample-app.local"
